//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bing_Search.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bing_Search.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单项 的本地化字符串。
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱搜索 的本地化字符串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 百度 的本地化字符串。
        /// </summary>
        public static string baidu {
            get {
                return ResourceManager.GetString("baidu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一维条码扫描 的本地化字符串。
        /// </summary>
        public static string barcode {
            get {
                return ResourceManager.GetString("barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倾力呈现 的本地化字符串。
        /// </summary>
        public static string best {
            get {
                return ResourceManager.GetString("best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必应 的本地化字符串。
        /// </summary>
        public static string bing {
            get {
                return ResourceManager.GetString("bing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱： 的本地化字符串。
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动对焦 的本地化字符串。
        /// </summary>
        public static string focus {
            get {
                return ResourceManager.GetString("focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谷歌 的本地化字符串。
        /// </summary>
        public static string google {
            get {
                return ResourceManager.GetString("google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一张 的本地化字符串。
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在IE中打开 的本地化字符串。
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一张 的本地化字符串。
        /// </summary>
        public static string prev {
            get {
                return ResourceManager.GetString("prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二维条码扫描 的本地化字符串。
        /// </summary>
        public static string qrcode {
            get {
                return ResourceManager.GetString("qrcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftToRight 的本地化字符串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-CN 的本地化字符串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫码结果 的本地化字符串。
        /// </summary>
        public static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给个好评吧！ 的本地化字符串。
        /// </summary>
        public static string review {
            get {
                return ResourceManager.GetString("review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存图片 的本地化字符串。
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海盗湾 的本地化字符串。
        /// </summary>
        public static string tpb {
            get {
                return ResourceManager.GetString("tpb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免费VPN注册方法（8.1适用） 的本地化字符串。
        /// </summary>
        public static string vpn {
            get {
                return ResourceManager.GetString("vpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进 的本地化字符串。
        /// </summary>
        public static string web_next {
            get {
                return ResourceManager.GetString("web_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退 的本地化字符串。
        /// </summary>
        public static string web_prev {
            get {
                return ResourceManager.GetString("web_prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网页： 的本地化字符串。
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新浪微博： 的本地化字符串。
        /// </summary>
        public static string weibo {
            get {
                return ResourceManager.GetString("weibo", resourceCulture);
            }
        }
    }
}
